DELETE FROM Dish
DBCC CHECKIDENT('Dish', RESEED, 0)

--INSERT INTO Dish (DishName, DiningHallID, MealTypeID, DateAdded)
--VALUES ('Fake Food', 1, 1, GETDATE()),
--('Fake Food', 1, 2, GETDATE()),
--('Fake Food', 1, 3, GETDATE()),
--('Fake Food', 2, 1, GETDATE()),
--('Fake Food', 2, 2, GETDATE()),
--('Fake Food', 2, 3, GETDATE()),
--('Fake Food', 4, 1, GETDATE()),
--('Fake Food', 4, 1, GETDATE()),
--('Fake Food', 4, 1, GETDATE()),
--('Fake Food', 4, 1, GETDATE()),
--('Fake Food', 4, 1, GETDATE()),
--('Fake Food', 4, 1, GETDATE()),
--('Fake Food', 4, 1, GETDATE()),
--('Fake Food', 4, 1, GETDATE()),
--('Fake Food', 4, 1, GETDATE()),
--('Fake Food', 4, 1, GETDATE())

DELETE FROM ExclusionKeywords
DBCC CHECKIDENT('ExclusionKeywords', RESEED, 0)

INSERT INTO ExclusionKeywords (Keyword, DishFilterID)
VALUES ('Pasta', 1),
('Yogurt', 1),
('Couscous', 1),
('Pies', 1),
('Cheesecake', 1),
('Tortellini', 1),
('Quesadilla', 1),
('Fries', 1),
('Corn', 1),
('Black Bean', 1),
('Cookies', 1),
('Tofu', 1),
('Mein', 1),
('Noodle', 1),
('Noodles', 1),
('Rice', 1),
('Risotto', 1),
('Toast', 1),
('Pancakes', 1),
('Cupcakes', 1),
('Brownies', 1),
('Pizza', 1),
('Quesadillas', 1),
('Macaroni', 1),
('Penne', 1),
('Gemelli', 1),
('Pie', 1),
('Chickpea', 1),
('Orzo', 1),
('White Bean', 1),
('Hash Browns', 1),
('Ravioli', 1),
('Potato Puffs', 1), 
('Farfalle', 1),
('Hash Brown', 1),
('Potato Wedges', 1),
('Whipped Potatoes', 1),
('Mashed Potatoes', 1),
('Potato Leek', 1),
('Chili', 1),
('Fusilli', 1),
('Capri', 1),
('Bacon', 2),
('Turkey', 2),
('Chicken', 2),
('Pork', 2),
('Sausage', 2),
('Tuna', 2),
('Bacon', 3),
('Turkey', 3),
('Chicken', 3),
('Pork', 3),
('Sausage', 3),
('Pasta', 4),
('Couscous', 4),
('Pies', 4),
('Cheesecake', 4),
('Tortellini', 4),
('Quesadilla', 4),
('Cookies', 4),
('Mein', 4),
('Noodle', 4),
('Noodles', 4),
('Toast', 4),
('Pancakes', 4),
('Cupcakes', 4),
('Brownies', 4),
('Pizza', 4),
('Quesadillas', 4),
('Macaroni', 4),
('Penne', 4),
('Gemelli', 4),
('Pie', 4),
('Ravioli', 4),
('Farfalle', 4),
('Fusilli', 4),
('Bacon', 5),
('Turkey', 5),
('Chicken', 5),
('Pork', 5),
('Eggs', 5),
('Yogurt', 5),
('Cheesecake', 5),
('Quesadillas', 5),
('Quesadilla', 5),
('Cookies', 5),
('Egg', 5),
('Toast', 5),
('Pancakes', 5),
('Cupcakes', 5),
('Brownies', 5),
('Pizza', 5),
('Cheese', 5),
('Sausage', 5),
('Tuna', 5),
('Capri', 5),
('Yogurt', 6),
('Cheesecake', 6),
('Quesadillas', 6),
('Quesadilla', 6),
('Cheese', 6),
('Capri', 6)

INSERT INTO MealType (MealTypeName)
VALUES ('Breakfast'),
('Lunch'),
('Dinner')

--DELETE FROM DiningTypes
--DBCC CHECKIDENT('DiningTypes', RESEED, 0)

INSERT INTO dISHFILTERS (filtername, filterDescription)
VALUES ('Paleo', 'No grains, potatoes, dairy, sugar and legumes.'),
('Vegetarian', 'No meat.'),
('Pescatarian', 'No meat except for seafood.'),
('Gluten-Free', 'No grains and products containing gluten.'),
('Vegan', 'No meat and dairy.'),
('Lactose-Free', 'No dairy.')

INSERT INTO DiningHall (DiningHallName, URL)
VALUES ('Wucox', 'http://facilities.princeton.edu/dining/_Foodpro/menuSamp.asp?locationNum=02&locationName=Butler+%26+Wilson+Colleges&sName=Princeton+University+Dining+Services&naFlag=1'),
('CJL', 'http://facilities.princeton.edu/dining/_Foodpro/menuSamp.asp?locationNum=05&locationName=Center+for+Jewish+Life&sName=Princeton+University+Dining+Services&naFlag=1'),
('RoMa', 'http://facilities.princeton.edu/dining/_Foodpro/menuSamp.asp?locationNum=01&locationName=Rockefeller+%26+Mathey+Colleges&sName=Princeton+University+Dining+Services&naFlag=1'),
('Forbes', 'http://facilities.princeton.edu/dining/_Foodpro/menuSamp.asp?locationNum=03&locationName=Forbes+College&sName=Princeton+University+Dining+Services&naFlag=1'),
('Whitman', 'http://facilities.princeton.edu/dining/_Foodpro/menuSamp.asp?locationNum=08&locationName=Whitman+College&sName=Princeton+University+Dining+Services&naFlag=1')